apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-vctf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-vctf
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-vctf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-vctf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-vctf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-abht-tenant/rhtap-demo-app/hacbs-test-project-vctf@sha256:e8c91a4a2098f7fb1ff78c7676bccdedfdea8ad12b7bc0e6298e18feb717f1bb
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
